### PR TITLE
Hardcode midterm data, file deletion, and grading file downloads 

### PR DESCRIPTION
**Pull request by abchilders**
This pull request adds the following features:

- Sample midterm data - the database contains starter code from a previous midterm to show how students can use the platform for programming exams. 
- File deletion - students can now soft-delete files from the Assignment view 
- Grading file downloads (see #31) - instructor can now download a ZIP file for an assignment containing students' submitted files and test results for that assignment

### CODE REVIEW

**Comment by acarteas** [comment]
This PR is rather large.  What would be appropriate acceptance criteria for this PR?

**Comment by abchilders** [comment]
- Midterm problems 1 through 6 are visible as assignments to anyone associated with the CS 211 course 
- When a user clicks the "x" on the tab for an uploaded file in the Assignments view, the file is soft-deleted in the database (is_deleted = 1) and the file is no longer visible on the website 
- In the Assignments view, An instructor of a course can enter the tab labelled "Student Results," click the "Download Details" button, and receive a ZIP download containing any files that students have uploaded for that assignment and a CSV file containing any student test results for that assignment

**Comment by acarteas** [comment]
@abchilders Please DM me on discord our github API key.

**Comment by abchilders** [comment]
Messaged you the API keys, leaving this comment as a reminder-- copy and paste the API keys into oauthconfig.json on both the client and server end.

**Comment by acarteas** [comment]
Looks good.

**Pull request merged**
