### PR TITLE
Manage tests

### LINKED ISSUE #36: Manage test cases within assignments
Allow instructors for a course to manage test cases for each of the course's assignments:

- [x] Let instructors create test cases from client 
- [x] If the result of running a test with a student's code is creating a new file, this file should be added to the assignment view. 
- [x] Minor enhancement: when reloading test cases (say, after creating a new one), either force the selected test case to be the first one in the list again OR force the displayed test case information to match the one selected. 
- [x] In bulk results view, highlight a test result when the date run of the test result < date that the files were last altered (i.e. if a test result was run before the user's files were last modified) 
    - [x] e1f2485cb900aca6f0c8bdd15477e816df1ccaf5 makes the "existsDateMismatch" endpoint obsolete; remove this endpoint/DB function after client is refactored to accommodate new DB changes
- [x] Have a "run all" button that runs test cases on behalf of all the students. 
    - [x] Can put the "run all" in a for loop with a promise chain: run a, get results from a, run b, get results from b, etc. --> send n requests to server 
- [x] Fix bug where if the current user has course permissions to grade/modify course, but isn't instructor or admin, then the bulk results table is fully populated with all of the current user's results (this is caused by a server-side check in getTestResults() where, if you're not an admin or an instructor, the server returns your own results instead of the ones belonging to the given student)

Preliminary tasks:
- [x] figure out what the client's currently doing; add comments as needed 
- [x] figure out why running tests as a different person (your student) doesn't work and fix it

### PR DESCRIPTION
**Pull request by abchilders**
Resolves #36. The following features should work properly before merging: 
- Instructors can create test cases using the Manage Tests tab in assignment view 
- If the result of running code is that a file is **created**, this file should be **added** to the assignment view 
- If the result of running code is that a file is **deleted**, this file should be **removed** from the assignment view 
- In the Student Results tab in assignment view, if the student uploaded or deleted a file at any time since running a test case, that test case should be highlighted in yellow on that student's row.
- Clicking the "Run all tests" button in the Student Results tab should run all test cases for all students, and subsequently display results in the table 
- File contents are visible without crashing in Assignment view 
- Docker containers are removed immediately after use (there shouldn't be any containers left running when code is done compiling and results are returned)

### CODE REVIEW

**Comment by acarteas** [comment]
Would @itravers be willing to check this one out for me?

**Comment by abchilders** [comment]
Tips--

To test any features that have to do with running code: log into the website as yourself. Then use the database to give yourself instructor privileges (set is_instructor = 1 in users table, set course_role = 12 in course_users table). Add the files I uploaded at https://github.com/abchilders/AutograderTestingFiles to your user and run these to test file creation/deletion. 

You can make a user's test results outdated by uploading or deleting a file at any point after running a test case; this should make their entry in the Student Results tab appear highlighted in yellow. 

Use Docker Desktop or run `docker ps -a` in your command prompt to view all Docker containers. There shouldn't be any remaining after code has finished running and the results are returned to you.

I've tested it on my end but I'd greatly appreciate a second pair of eyes, ideally one working on a different machine :) thank you so much!

**Comment by acarteas** [comment]
Okay, I'll try to take a peek before the end of the weekend.

**Comment by acarteas** [comment]
Looking at this now...

**Comment by acarteas** [comment]
I'm getting this when I try to run a test case:

image

**Comment by abchilders** [comment]
Oh, bother. I'll see what I can do. Can you see the contents of the object? It looks like something on the server might sending back an HTTP status instead of an actual result.

What files did you upload before running a test case? And when you log in as a user, in the database, do you know if your user has is_admin/is_instructor permissions in the users table, and what your course_role is in the course_users table? 

I suspect it might either be a login issue or a compiler issue, but I've only gotten the error once or twice myself, so I'm trying to figure out how to reproduce it.

**Comment by abchilders** [comment]
Or! Another proposition: could be that I forgot to specify that some function on the client needs to return an HTTP response.*data* back to the test cases component, not just the response itself. I'll work on it this afternoon.

**Comment by acarteas** [comment]
I followed your instructions and copied over the files on your github link.  I then clicked "run test case" or whatever, selected the first option, and clicked run.

**Comment by abchilders** [comment]
Fixed, hopefully. See commit bc200db. I think the error may have been due to a bug in the way that the client handles responses from the server when either of these occurs:
- your login session expired for some reason???, so the server returns `result.data.response = false`
- your code produced no output, so the server returns "", which the client previously would have flagged as an error 

The fix for TestCasesDb.js on the client is a little hacky-- see lines 35-39 of that file-- but leaving the state variable `test_result = ""` and then using that condition to determine whether to render the "Test Results" window or not made more sense than trying to change its default value to something that makes its intentions less obvious. If you can think of a better way to handle it, feel free to change it.

If that doesn't help, maybe the Docker daemon's not running?
Full steps that I follow: 
- start Docker desktop and wait until it's running 
- update server/oauthconfig.json and client/src/oauthconfig.json with client_id and client_secret 
- start server with `server node.js`; start client with `npm start` 
- log into website with GitHub 
- add the CS 211 course
- edit database to set is_instructor = 1 in users table and course_role = 12 in course_users table 
- log out and in again so that the is_instructor bit takes effect 
- add testing files from the repo I linked 
- run any test case (I choose Simple Add) 
- I get this: 

image

**Comment by acarteas** [comment]
works now.  Good job.

**Pull request merged**
